### ISSUE TITLE
Links to download software do not work

### ISSUE THREAD

**Issue by xpagesbeast** [IBM/domino-docker#11]
The links to download Domino do not work.  This repository needs to consider someone who read a marketing add about Domino or heard a person from the Domino community raving about how great Domino is to a person who never heard of it.

The links to the community edition need to be available to anyone without having to talk to IBM/HCL sales or contacting a IBM business partner.

Information about Domino designer and Domino Administrator have to be mentioned and also Appdev pack.  A novice person will think the download has all the features or at least have options to choose the features.

**Comment by Daniel-Nashed** [comment]
We are working on adding the Domino Community edition.
The download for the Community Edition is separate and I agree, we should make it easier to get started.
The first step will be to add "Domino CE" to the installable version. 
A next step will be to add software to the Domino base install. 

Here is what I am currently working on:

10.0.1 FP1 support
Docker CE support
Build the foundation for add-on products.
The Proton servertask and the DSAPI are separate today and we need to find a simple way to install and configure them.

But we have to wait for the next iteration of the AppDev pack to see how we can get this scripted in an easy way. Installing the software is the smallest part in this case.

**Comment by thampel** [comment]
Links have been updated to reflect a flat folder structure

**Comment by xpagesbeast** [comment]
Thanks for adding the community edition, the other links are still taking us to broken pages.  I'd remove any broken links, some users may never try the community editing links because they think all links are broken as they go down the line (community edition are the last links)....  Or move Community Edition to above the other broken links so they try those first.

**Comment by Daniel-Nashed** [comment]
That's kind of odd! If you copy the link it works. If you use the link on the page, it says application error.
The IBM PA download website is weird! 
I agree it would be a good idea to list the Community Edition first.

We are preparing a check routine that you can run before starting the build to show missing software including links. The links I worked with are similar to the links here. Just without the www number.

Here is an example:

https://www.ibm.com/software/howtobuy/passportadvantage/paocustomer/sdma/SDMA?P0=DOWNLOAD_SEARCH_BY_PART_NO&FIELD_SEARCH_TYPE=3&searchVal=CNW1ZEN

Let's see if this works here...

-- Daniel

**Comment by Daniel-Nashed** [comment]
Interesting the same link here works for me. But not on the documentation page.
