### ISSUE TITLE
Missing LANG documentation

### ISSUE THREAD

**Issue by tcsoft** [IBM/domino-docker#25]
The environment variables documentation is missing valid options for the LANG option.
Please supply the possible options or a link to the list if it's elsewhere on the Internet.

Thanks in advance for your assistance.
Vielen Dank im Voraus für Ihre Hilfe.

**Comment by Daniel-Nashed** [comment]
The LANG options belong more to the Domino server / Linux than to the Git project.
Locales are a standard on Linux.
You can list all installed locales via

`locale -a 
`
But you have to be a bit careful! Current Linux versions don't provide all locales out of the box. 
We have added a way to add more locales to the image. But this doesn't work for all platforms! 
For example if you use the UBI base image, the German locale is missing.

I will have a look again and provide some documentation.

We missed this issue.. it has been a while.. Sorry! if you have additional feedback/questions let me know.

**Comment by Daniel-Nashed** [comment]
Closing, because we never heard back.
