### ISSUE TITLE
Store Notes ID files for users in file system

### ISSUE THREAD

**Issue by rsielken** [IBM/domino-docker#26]
When a Domino user is generated (often through a command line option), the Notes ID file should be stored in the Domino Data directory.  While it can be extracted from the person document, it is easier if it is already there.  In particular, the Admin user's Notes ID file is needed to perform other actions (and using the server.id to get the admin's ID is a bit hacky).

**Comment by Daniel-Nashed** [comment]
The automatic setup isn't really production ready as it is today.
But we support all options that the current Domino 11 setup supports.
So you can specify a file location for the admin.id.

With Domino V12 and the One Touch/One File setup there will be support for automatic ID Vault setup - -which would be the safer option to store the ID.

We will continue to look into more features added in Domino V12 take benefit of them as soon they are available in Domino
