### ISSUE TITLE
Include public SSL server certificate in file system

### ISSUE THREAD

**Issue by rsielken** [IBM/domino-docker#27]
When SSL is configured, the keyfile is created and Domino is configured to use it.  The certificate is self-signed so the users will either need to accept a browser exception or install the certificate into the OS and trust it.  While a browser can be used once HTTP is running to extract the certificate, it would be nicer/easier if the certificate was a file in the file system that could be downloaded and installed directly and through more avenues than just the browser.  This would normally the be .cer, .p12 or .pfx that was used to generate the keyfile.kyr.

Of course, customers should eventually use real/trusted certificates, but in the mean time, it would make these untrusted certificates easier to use.

**Comment by thampel** [comment]
Very true. We thought of integrating LetsEncrypt for Domino (LE4D) - https://www.midpoints.de/de-solutions-LE4D and also thought of an option to define the name of an existing .cer file to be used.

**Comment by Daniel-Nashed** [comment]
To add what Thomas said and to give some background what we currently have implemented ... 

It's a complex topic. We currently have environment settings which can be used to copy keyring files. The parameter can be either a file location or a HTTP/HTTPS link. 

By default we automatically create a local CA with a well defined certificate including SAN etc. which is used to create a keyring file for the hostname of the machine.
We have added the functionality for the Volt image, but added it to the underlying Domino image.

This is the default behavior and we have a way to import existing keyring files.
You can also use a notedata.zip when you create a container which will allow to add your own NSF/NTF etc and other data. This also allows to add keyring files. 

Having LetsEncrypt support would allow just to pass a configuration without the requirement to pass files. And this would also allow certificate update. 

The challenge isn't just the first deployment of a certificate but also the update.
There are plans for Domino 12 for enhancements in that area -- not just for Domino Docker.
So the main question here is how urgent we need additional auto deployment functionality for certificates today.

What we build today is a simple auto certificate deployment. 
We can add a way to pass a p12 and convert it to a keyring file. that's a simple enhancement. The code is already there.

And we have a deployment way for keyring files thru files like Docker secrets and HTTP/HTTPS downloads on deployment.

**Comment by stefanopog** [comment]
One thing. Self-signed certificates may break NodeJS APIs. 
There is. workaround, but it is boring

**Comment by Daniel-Nashed** [comment]
> 
> 
> One thing. Self-signed certificates may break NodeJS APIs.
> There is. workaround, but it is boring

There is a difference between a real "self-signed" cert and a cert from your own CA.
We create a local CA and derive certificates from there.
In the case of the Docker image we don't export the CA currently but remove it.
This gives you just a technically good looking certificate.

But you can use the certificate scripts to generate certificates outside the Docker image and keep the CA. 

A simple self-signed certificate is on-the-fly without a root certificate form a CA.
That is difficult to get trusted. But you can trust the local CA.
What I do for my test environments is to derive all my certs from this CA and distribute it.

Not all environments have external access. So you might not be able to get a commercial CA for a local domain. And you cannot use LetsEncrypt if you are not exposed to the internet.

So a local CA can be helpful. But we can't build that into the image. We can either create something on-the-fly locally or get a certificate be imported. Today with a keyfile you specify.

Does that make sense and help?

**Comment by Daniel-Nashed** [comment]
Domino V12 Beta1 has been released this week.
One of the new features is the CertMgr, which supports automatic certificate creation with Let's Encrypt. 
And you can also request certificates via 3rd party CAs using a very easy to use workflow.
CertMgr in combination with the cerstore.nsf is the new Domain wide certificate management solution.

Our script will continue to automatically create a kyrfile as a starting point.
But you can be sure that we have a very close look what Domino V12 will provide and have already started to integrate new functionality like the one touch/one file setup. And you can expect that we will leverage new functionality in Domino V12 as soon they become available in a way we can integrate them :-)
