### ISSUE TITLE
Use CLA Assistant for contributions

### ISSUE THREAD

**Issue by paulswithers** [IBM/domino-docker#3]
I came across this some months ago, but it seems a good option to use for contributions. It's already used on some other IBM projects. See e.g. [http://github.com/watson-developer-cloud/java-sdk](https://github.com/watson-developer-cloud/java-sdk).

https://cla-assistant.io/watson-developer-cloud/java-sdk

https://cla-assistant.io/ is a hosted version. https://github.com/cla-assistant/cla-assistant shows the details

**Comment by Daniel-Nashed** [comment]
it's enabled after the move to HCL
