### ISSUE TITLE
Source code for DominoUpdateConfig.jar

### ISSUE THREAD

**Issue by eivindr** [IBM/domino-docker#30]
Any plans on making the source code for 'DominoUpdateConfig.jar' open source?

**Comment by Daniel-Nashed** [comment]
Sorry we missed this request and we meanwhile removed any components, which are not open. The only C code left is compiled inside the build container when configured. The JAR is not needed for Domino 12 OneTouch configurations. We removed all older automation setup routines and want to encourage all admins to move to Domino 12.x with full automation support using OneTouch setup native implemented in Domino 12.x.

It is now all fully integrated.

Thanks
Daniel

**Comment by Daniel-Nashed** [comment]
Sorry we missed this request and we meanwhile removed any components, which are not open. The only C code left is compiled inside the build container when configured. The JAR is not needed for Domino 12 OneTouch configurations. We removed all older automation setup routines and want to encourage all admins to move to Domino 12.x with full automation support using OneTouch setup native implemented in Domino 12.x.

It is now all fully integrated.

Thanks
Daniel
