### ISSUE TITLE
AdminIDFile parameter in env_domino not working

### ISSUE THREAD

**Issue by jmoralesarambulo** [IBM/domino-docker#32]
Hi,
I'm new to Domino but I love the idea of Domino on Docker! Nice job guys!!

I use --env-file parameter when I execute the docker run command ... and when I add to the env_domino file the variable:
AdminIDFile=/local/notesdata/admin.id

no id file is created in the path /local/notesdata/

**Comment by Daniel-Nashed** [comment]
Sorry we have not seen this question earlier..

We are using what Domino offers with the standard setup and "just" make it available over environment configuration.
In the standard setup this is an input and not an output parameter.  
You don't need to specify an admin for a 2nd server in the domain. This is only needed for the first server.

Here is an example what you would use for a 2nd sever:
```
  isFirstServer: "false"  
  ServerName: domino-acme-02   
  ServerIDFile: http://192.168.96.170/software/domino-acme-02.id  
  OtherDirectoryServerName: domino-acme-01   
  OtherDirectoryServerAddress: domino.acme.com   
```
