### ISSUE TITLE
cert.id default password

### ISSUE THREAD

**Issue by klehmann** [IBM/domino-docker#33]
What's the cert.id password when I run the example command to set up a new server?

```
docker run -it -e "ServerName=Server1" \
    -e "OrganizationName=MyOrg" \
    -e "AdminFirstName=Thomas" \
    -e "AdminLastName=Hampel" \
    -e "AdminPassword=passw0rd" \
    -h wien.demo.com \
    -p 80:80 \
    -p 1352:1352 \
    -v dominodata_demo1:/local/notesdata \
    --stop-timeout=60 \
    --name server1 \
    hclcom/domino:11.0.1
```

**Comment by ANornes** [comment]
Hi,

Can't you specify password with  -e "OrganizationPassword=passw0rd"  ?

edit:
and Certifier with -e "OrganizationName=Cert"

**Comment by klehmann** [comment]
Yes, I can and it's working. That line should probably be added to the sample code, because otherwise the created server has limited use, e.g. you cannot register more users than the admin.

**Comment by Daniel-Nashed** [comment]
the code examples have it. but I added it to the example in the documentation you referenced.
thanks!
