### ISSUE TITLE
Which domino software package do i need ?

### ISSUE THREAD

**Issue by johannes-decker-ads** [IBM/domino-docker#38]
I tried to build a domino image as you described in your repository. I downloaded Domino_12.0_DockerImage.tgz from Flexnet and copied it to the software directory of my local clon from your repository. Than I tried to execute the ./build domino command from the root directory and the required software package for domino on docker could not been found. So which package of the domino server do I have to download from Flexnet, to execute your build script ?

> [jdecker@ims-testserver domino-docker]$ ./build domino
-bash: ./build: Datei oder Verzeichnis nicht gefunden

**Comment by Daniel-Nashed** [comment]
first of all the error message might indicate that you are in the wrong directory. the build script should give you a different error message. 
The build environment will tell you which package to download. It's the Domino server webkit. the software that you would install if you install Domino native. Not the Docker image from HCL.

Having said that we have a dockerfile_hcl which can be used to build our image on top of the HCL image. 
This will require that you upload the HCL Docker image to your Docker environment first and we would base our image on to of the official HCL image. 

But I would recommend using the web kit instead to install it from scratch. 

You say "root" directory. To build you need to run the following command from the main directory in the git repository that you cloned. the directory that contains the build.sh script.

```
./build.sh domino
```

I hope this helps?

-- Daniel

**Comment by Daniel-Nashed** [comment]
closing because I didn't hear anything back.
