### ISSUE TITLE
Management Scrip

### ISSUE THREAD

**Issue by NixGi** [IBM/domino-docker#40]
Hi,
sadly, the link to the management script documentation is broken. I receive a 404.
Thanks
Frank

**Comment by Daniel-Nashed** [comment]
can you please be more specific which link you mean?

Thanks
Daniel

**Comment by NixGi** [comment]
![management-link](https://user-images.githubusercontent.com/64532731/132815729-e230afc0-8b51-4153-9694-eb81268fbfb4.PNG)

**Comment by Daniel-Nashed** [comment]
Thanks! Fixed the link. The file moved to the docs folder.

But depending on what you do, you might want to switch the new script documented here:

https://blog.nashcom.de/nashcomblog.nsf/dx/introducing-domino-container-script-for-podman-an-docker.htm

There is no full documentation in the start script yet.  But the blog post has all the details.

We want to replace the functionality of the management script completely with this domino_container script.

If you have feedback, let me know.

-- Daniel
