### ISSUE TITLE
Failed Domino 11.01FP4 build on CI/CD Pipeline in Bitbucket

### ISSUE THREAD

**Issue by NicolasKarnick** [IBM/domino-docker#42]
Hi, 

building a Domino 11.0.1 Server with Fix Pack 4 is failing in our CI/CD Pipeline at Bitbucket. When I build a normal 11.0.1 Server it works like a charm.  But there is an issue when the fix pack is installing. This Problem also occurs with FP3. So its not a general FP4 issue!

### TL;DR
`tar` command in FP4 `tools//lib` directory causes bitbucket build crash for domino 11.01FP4 Server due to missing `--no-same-owner` argument

-----------------------------------

The Dockerfile is based on `centos:7.9.2009`. Otherwise, nothing special. Im using an older Dockerfile with the User Notes but that should not be a problem.

```
FROM centos:7.9.2009

USER root

# Copy Install Files to container
COPY install_dir $LocalInstallDir
COPY duplycron /etc/cron.d/duplycron

# Prepare environment for Domino
# Update, Install required packages and run separate install script
RUN yum update -y && yum install -y epel-release sudo
RUN yum install -y openssl  bc which wget nano unzip rsync lsof gdb sysstat file net-tools python3-pip python3-dev duply duplicity && \
  pip3 install boto3 && \
  $LocalInstallDir/install_domino.sh && \
  yum clean all >/dev/null && \
  rm -fr /var/cache/yum && \
  rm -rf $LocalInstallDir

HEALTHCHECK --interval=60s --timeout=10s CMD /domino_docker_healthcheck.sh

# Expose Ports NRPC HTTP POP3 IMAP LDAP HTTPS LDAPS IMAPS POP3S DIIOP DIIOPS
EXPOSE 1352 80 110 143 389 443 636 993 995 63148 63149

ENTRYPOINT ["/domino_docker_entrypoint.sh"]

USER notes

RUN crontab /etc/cron.d/duplycron
```

My `bitbucket-pipeline.yml` looks like that:

```
image: eclipse-temurin:11-jre-focal
#atlassian/default-image:2

pipelines:
  default:
    - step:
        name: Build and Test
        script:
          - chmod +x build.sh
          - cd dockerfiles/domino
          - chmod +x build_domino.sh 
          - cd install_dir
          - chmod +x install_domino.sh
          - chmod +x domino_install_data_prep.sh
          - cd ../../..
          - ./build.sh domino
        services:
          - docker
        caches:
          - docker
```
Build Configuration at the beginning of the build:

```
Build Configuration
--------------------------------------------------------------------------------
DOWNLOAD_FROM      : []
SOFTWARE_DIR       : [/opt/atlassian/pipelines/agent/build/software]
PROD_NAME          : [domino]
PROD_VER           : [latest]
PROD_FP            : []
PROD_HF            : []
PROD_EXT           : []
CHECK_SOFTWARE     : [yes]
CHECK_HASH         : []
DOWNLOAD_URLS_SHOW : []
TAG_LATEST         : []
DOCKER_FILE        : []
LinuxYumUpdate     : [yes]
Getting current software version from [/opt/atlassian/pipelines/agent/build/software/current_version.txt]
Product to install: domino 11.0.1 FP4 
Checking software via [/opt/atlassian/pipelines/agent/build/software/software.txt]
11.0.1              [OK]  Domino_1101_Linux_English.tar  (-)
11.0.1FP4           [OK]  Domino_1101FP4_Linux.tar  (-)
```

The `build.sh` output at the end of base 11.0.1 Server:

```
Downloading Domino Installation files ...
Successfully downloaded, extracted & checked: [http://172.17.0.2/Domino_1101_Linux_English.tar] 
Successfully downloaded, extracted & checked: [http://172.17.0.2/Domino_1101FP4_Linux.tar] 
--------------------------------------------------------------------------------
Installing domino 11.0.1
--------------------------------------------------------------------------------
Running Domino Silent Install -- This takes a while ...
Domino installed successfully
```
When it comes to the fix pack installation, the problem starts:

```
--------------------------------------------------------------------------------
Installing Fixpack 11.0.1FP4
--------------------------------------------------------------------------------
Running Domino Fixpack Silent Install -- This takes a while ...
--------------------------------------------------------------------------------
HCL Domino for Unix Install Program
------------------------------------
Installer is initializing. It may take a few minutes, please, wait.
WARNING:
The following system commands were not located:
  rsh
Installation to remote systems will not be possible.
Mon Nov 29 16:07:57 CET 2021
Batch mode script file is:  /tmp/install/domino_fp/linux64/domino/script.dat
Validating...
Installation settings for host 9c86ed220c74:
    Program directory    : /opt/hcl/domino
    Data directory       : /local/notesdata
      UNIX user          :   notes
      UNIX group         :   notes
11000100 upgrade to 1101FP4
Not checking patches for linux.
Installing  Domino Server kits ...
Replacing <NOTESDATADIR>lndfr.ntf
[...]
Replacing <NOTESDATADIR>dwa9W.cab
Fatal Error extracting filegroup.
cd /opt/hcl/domino/notes/latest/linux; /usr/bin/cat /tmp/install/domino_fp/linux64/domino/sets/fgroups/fg2.taz | gunzip -c | /usr/bin/tar xvf -
./
./jvm_patch.diff
/usr/bin/tar: ./jvm_patch.diff: Cannot change ownership to uid 252601139, gid 252600513: Invalid argument
./tika_pdf_sort.xml
/usr/bin/tar: ./tika_pdf_sort.xml: Cannot change ownership to uid 252601139, gid 252601622: Invalid argument
/usr/bin/tar: .: Cannot change ownership to uid 252601139, gid 252600513: Invalid argument
/usr/bin/tar: Exiting with failure status due to previous errors
--------------------------------------------------------------------------------
Failed - Fixpack Installation failed!!!
```

The Issue for that behaviour is described here
[https://github.com/habitat-sh/builder/issues/365#issuecomment-382862233](url)

In my local WSL2 Environment (Ubuntu 20.04), it all works correctly. 
I also changed the build environment from `eclipse-temurin` to `ubuntu` but the problem persists.

I found the Problem in the following lines at `Domino_1101FP4_Linux\linux64\domino\tools\libInstBE.pl`:

```
if (! $ENV{'NUI_NOUNTAR'}) {
				    @sb = stat($destPath);
				    $fgroup{$destPath} = $sb[5];
				    $fuid{$destPath} = $sb[4];
				    $fmode{$destPath} = $sb[2] & 07777;
				$cmd = 
					"cd $destPath; " .
					"$Sys::cat $fgset | " .
					"$uncompressCmd -c | $Sys::tar xvf -";
				$dbg && print "    extract cmd: $cmd\n";
				$dbg && print "    extracting " . `date`;
				$out = `$Sys::sh -c "$cmd" 2>&1`;
				$stat = ($? >> 8);
				if ($dbg) {
					print "    stat: $stat\n";
					print "    out: $out";
				}
				if ($stat) {
					Out($txt{6} . $cmd . "\n" . $out);
					return 0;
				}
				    chown($fuid{$destPath}, $fgroup{$destPath}, $destPath) or 
					die "can't change owner back on $destPath:$!";
				    system("$Sys::chown -R $fuid{$destPath}:$fgroup{$destPath}  $destPath") ;
				    
				$dbg && print "    done " . `date`;
				}
```
at line 887  `"$uncompressCmd -c | $Sys::tar xvf -";`

And fixed it in your `install_domino.sh` script at `\dockerfiles\domino\install_dir` with the addition:

```
if [ ! -z "$INST_FP" ]; then
    header "Installing Fixpack $INST_FP"

    echo
    echo "Running Domino Fixpack Silent Install -- This takes a while ..."
    echo

    pushd .
    cd domino_fp/linux64/domino
    sed -i '887s/"$uncompressCmd -c | $Sys::tar xvf -";/"$uncompressCmd -c | $Sys::tar xvf - --no-same-owner";/' tools/lib/InstBE.pl

    ./install -script script.dat > $INST_FP_LOG

    check_file_str "$INST_FP_LOG" "$FP_STRING_OK"

    if [ "$?" = "1" ]; then
    	echo
      log_ok "Fixpack installed successfully"

      # Store Domino Fixpack Information
      set_domino_version fp

    else

      echo
      print_delim
      cat $INST_FP_LOG
      print_delim
      log_error "Fixpack Installation failed!!!"
      popd
      exit 1
    fi

    popd
    rm -rf domino_fp

  fi  
```
`sed -i '887s/"$uncompressCmd -c | $Sys::tar xvf -";/"$uncompressCmd -c | $Sys::tar xvf - --no-same-owner";/' tools/lib/InstBE.pl`

Adding this, the build works again and the fix pack is installed correctly

```
Running Domino Fixpack Silent Install -- This takes a while ...
Fixpack installed successfully
```

Don't know if this is a known issue but it could safe days. Except for me ;)

**Comment by Daniel-Nashed** [comment]
This is kind of odd. I just did another build to verify. It works here.

I am running on CentOS Stream 8 with Docker  20.10.10 building with the standard CentOS Stream 8 base image.  
And I don't see any issue. So this does not look like a general issue with 11.0.1 FP4.  
You are also stating that your environment with WSL and Ubuntu works. 

I don't know what is different in your build environment. We are starting a CentOS Stream 8 based build image.  
And I would assume it behaves the same on different build environments.

What I also don't understand why your are invoking a build container to build inside our build container.   
The script is intended to build either with Docker or Podman directly. 

It looks like your environment is behaving differently at some stage. But I don't see why this only happens with FP4. 
Did you compare the files from FP3?  The build process is running with the root user. We can change any file ownership. But we are not trying to touch the Domino installer in any way unless there is a good reason for it.

If it works natively and also with a Docker reference environment, this doesn't look like a more general issue with 11.0.1 FP4.  But then the same build worked before with FP3, having a look into the files in FP3 and FP4 from owner point of view, could be helpful. Sadly I cannot spend time on any analysis. But if someone finds a difference in the permissions that could be fixed by HCL, I would volunteer to check with HCL for you.

Thanks for your detailed analysis!

Daniel


````
./build.sh domino 11.0.1 FP4

Completed in 7 minutes and 34 seconds

hclsoftware
hclsoftware
Stopped & Removed Software Repository Container

Completed in 7 minutes and 35 seconds
````

**Comment by NicolasKarnick** [comment]
Hey Daniel, thanks for your answer. 
That's not a general issue with FP4. The problem also occurs when trying to install FP3. 

Due to the fact that the build works correctly on my local environment, I assume that there has to be a difference when building the 11.0.1FP3/FP4 with the bitbucket Pipeline.

> What I also don't understand why your are invoking a build container to build inside our build container.

Thats what bitbucket does: _"Bitbucket Pipelines runs your builds in Docker containers. These containers run a Docker image that defines the build environment. You can use the default image provided by Bitbucket or get a custom one."_
My custom one is the `eclipse-temurin` Image due to the fact that the image is small and the build is faster

Because this works for 11.0.1 base install, I thought this should work for fix pack installation, too. But it doesn't.

I know that manipulating a Domino FP File doesnt sound like a good approach but that was the only way for me to get the installation process to work in bitbucket. 

Maybe theres a general issue with fix pack installation in a build environment like bitbucket or so. Maybe HCL hasnt tested it yet. I dont know. But reading this issue could maybe help others who stumble across this problem ;)

**Comment by Daniel-Nashed** [comment]
I thought FP4 fails and FP3 works. So it sounds like some permissions might be different.  
If you extract manually and see differences, let me know and we can find out if HCL wants to address this in a future FP.  
I discussed this with a friend and we both think it has something to do with the way permissions are handled in your build environment.  

Sadly we cannot look into all environments on our own. I am personally having a big zoo of environments already.  
But that's where the community comes into play. We are fixing anything in the community image that makes sense and helps. We cannot test every scenario. Also HCL cannot test all environments. This is a very special install scenario.   
And I now understand why this is a container inside a container. If this is a rights issue, maybe other software has similar issues and they can also look into it on their end?

Our build process is always started as root. We only switch back to the `notes` user --> id `1000` at the very final stage of the build.

**Comment by NicolasKarnick** [comment]
Yeah I totally understand. I will update my first post so that its clear that the problem occurs with the fix packs in general. 
Thanks for your time. 

I will inform you when I have updates regarding this issue.

**Comment by Daniel-Nashed** [comment]
Closing as not a problem with our build script directly.
