### ISSUE TITLE
Cannot build an image on a M1 Mac

### ISSUE THREAD

**Issue by edy** [IBM/domino-docker#43]
Hi,

i tried to build a domino image on a Mac with a M1 chip (ARM) and at first it failed. I use a freshly installed Rancher Desktop instead of Docker Desktop.

After executing `./build.sh domino` i got an error which stated that domino wouldn't support the hardware architecture. The build argument `--platform linux/amd64` helped me to get rid of that mesage. After a couple of minutes while domino was installing, the JRE crashed with a SIGSEGV. I found out, [settings the enviroment variable `QEMU_CPU=max`](https://github.com/docker/for-mac/issues/5561) would help and i have **successfully** built a runnable image.

Here's my `git diff` which i would like to see in this project. I think that these changes would be also necessary in all other dockerfiles and build scripts but am not able to test them due to missing installation files in my company.

```diff
diff --git a/dockerfiles/domino/build_domino.sh b/dockerfiles/domino/build_domino.sh
index 2483db7..619e549 100755
--- a/dockerfiles/domino/build_domino.sh
+++ b/dockerfiles/domino/build_domino.sh
@@ -250,7 +250,7 @@ docker_build ()
   fi

   # Finally build the image
-  $DOCKER_CMD build --no-cache $DOCKER_NETWORK \
+  $DOCKER_CMD build --platform linux/amd64 --no-cache $DOCKER_NETWORK \
     -t $DOCKER_IMAGE $DOCKER_TAG_LATEST_CMD \
     -f $DOCKER_FILE \
     --label maintainer="thomas.hampel, daniel.nashed@nashcom.de" \
diff --git a/dockerfiles/domino/dockerfile b/dockerfiles/domino/dockerfile
index 3df6a43..487a907 100644
--- a/dockerfiles/domino/dockerfile
+++ b/dockerfiles/domino/dockerfile
@@ -5,7 +5,7 @@
 ############################################################################

 FROM quay.io/centos/centos:stream8
-
+ENV QEMU_CPU=max
 # External arguments with a default value
 ARG BASE_IMAGE=
 ARG LinuxYumUpdate=
```

**Comment by Daniel-Nashed** [comment]
Thanks for your feedback and very cool!
I sadly have no Mac at all currently. So I can't test.
But this is a easy change to add. I will make it more flexible. 
I will add special build arguments, which can be used to specify custom build arguments.

I have to check how I can best add the `ENV` variable.
Does the `ENV` variable need to be set in the Dockerfile or would this also work exporting it in the build environment before the build command? Can you check if that works as well?

I am working on a new `next` branch, where all the Dockerfiles and much more is consolidated. 
The new project will only support Domino 12.0+ with the One-Touch setup and removes legacy components.

So this addition would go into the `next` branch directly. 
Do you have a reference for `QEMU-max` for me?

How did you build it? with nerdctl ? 
The current script officially does not support nerdctl. But you can configure it manually.
The next branch supports it already and automatically detects it...

Thanks
Daniel

**Comment by edy** [comment]
> I have to check how I can best add the `ENV` variable. Does the `ENV` variable need to be set in the Dockerfile or would this also work exporting it in the build environment before the build command? Can you check if that works as well?

I think you have to add an ARG variable for this to pass the max value from the build.sh.

> So this addition would go into the `next` branch directly. Do you have a reference for `QEMU-max` for me?

https://qemu-project.gitlab.io/qemu/system/arm/cpu-features.html
 
> How did you build it? with nerdctl ?

I didn't change the build script besides the platform arg, so the docker cli was used to build the image

**Comment by Daniel-Nashed** [comment]
Oh you are using a Docker environment. I used the build with `nerdctrl` cool if both work!
I never used the ENV statement. If also ARG works, this is easy to pass by the `docker build` command. there are many options already passed that way.

I am happy to add it to the next branch if you can come up with something I can integrate. 
Because I don't have a Mac, I can't test what would work.

From what I saw those options should be not the default, to ensure we are not breaking other builds.
But if you want it automatic if nothing is set, I need a way to detect a M1 chip via script...

**Comment by Daniel-Nashed** [comment]
@edy I didn't hear anything back. Did you get it working? I don't just want to close the issue without a solution.

Thanks
Daniel

**Comment by zeromancer1972** [comment]
@edy call me stupid but which file is this you edited to run on M1? I would like to test that here, too.

**Comment by edy** [comment]
@Daniel-Nashed sorry for my late response. Sometimes the build process gets stuck and no image would be built. I don't know what the reason is.

@zeromancer1972 

the first file is `dockerfiles/domino/build_domino.sh`, the second is `dockerfiles/domino/dockerfile`

**Comment by Daniel-Nashed** [comment]
thanks @edy  I just pushed a change to the develop branch with the '--platform' change. setting it explicitly does not harm the other platforms.
do you still need the `QEMU=max` set? 

it looks like it should be set automatically --> https://github.com/docker/for-mac/issues/5485

And I don't see why an environment variable passed to QEMU. 

Adding the ENV variable would also not harm. but I would only add it if still needed.

**Comment by edy** [comment]
Thank you. I don't neet the variable to be set if `-cpu max` is already set

**Comment by Daniel-Nashed** [comment]
I added the platform and I hope it works now. I cannot test it.  
Let me know if there is anything left to change.

Thanks for your feedback! 
I don't have a Mac with a M1 to test on my own.

-- Daniel
