### ISSUE TITLE
no such repo being called in many files hclcom/domino

### ISSUE THREAD

**Issue by westteck** [IBM/domino-docker#46]
Trying to run the scripts to install domino in a docker container and it fails trying to connect with either a git repo or a dockerhub repo named hclcom/domino. It is also listed in several of the readme.md files here. for example in the file docs/howto_docker-run.md it lists this repo, The repo does not exist anywhere I can find.

Please help

**Comment by Daniel-Nashed** [comment]
Not sure I can follow your problem description. You are trying to install it `into` a container?
`hclcom/domino` is the name of the resulting image. The name did not change and wasn't the repo name.  
Did you look into the documentation how to build the image? you just run the `./build.sh domino` command on command line and it will use Docker to build the image. 

Can you share the steps you do to build it and which error message you get? 

Here is the quick start link -> https://opensource.hcltechsw.com/domino-container/quickstart/

Thanks

Daniel

**Comment by westteck** [comment]
Hello Daniel, That is exactly what I did is follow the quickstart guide from the build image step. I followed the steps with no errors until the domino_container start step, that is when I get the first and only error. it is in the domino_container script that it tries to pull a dockerhub repo. clip of the script: it says GitHub image, but docker doesn't pull images from GitHub as far as I am aware. anyway, the user hclcom is not on dockerhub or github. but that is where it fails.

CONTAINER_NAME=domino

# Domino Docker Community/GitHub image
CONTAINER_IMAGE=**hclcom/domino**

# Standard HCL image
#CONTAINER_IMAGE=domino-docker:latest
![Screen Shot 2022-05-08 at 10 16 16 PM](https://user-images.githubusercontent.com/6167590/167346787-8db0f083-c367-451d-8f77-6e8492043932.png)

**Comment by Daniel-Nashed** [comment]
the quickstart clearly states you have to download the software and build an image.  
did you do that? and if yes, you might have an issue with the name of the image that you build.
the default build should create `hclcom/domino:latest`. 

I can't help you with limited information. I need the full info about what you did. Not just the last step what is not working.

**Comment by westteck** [comment]
I did download the software from flexnet. the last one I have is version 12.0.0. I was incorrect about the repo problem, the quickstart process did create a local image named hclcom/domino:12.0.0. Sorry just another learning opportunity. :) . So I edited the container_domino script with the image name of hclcom/domino:12.0.0 as that is the name of the image. now it builds the container named domino, but it doesn't start corectly it says the port 443 is allocated. I'm gonna burn this server and try another fresh server. I will post again if I have the same issue. I will also get the lates ver 12 of domino server. That might be some of the problems as well as my lack of experience. But if I set this up another dozen times or so I WILL learn it. lol Thanks

**Comment by Daniel-Nashed** [comment]
When building with an explicit version specified, the build process does not add the `latest` tag by default. Any custom tag with the `-tag=xyz` option or tag the image later with `docker tag ..` can be specified. 

The quickstart only works 1:1 if you are using the exact step. 

Port in use usually is an issue with another container or some other software blocking the port.
You can start without port 443 for a first test and there is also a Linux command to find out which process is using the port.

Linux command to list processes with application. If it is another Docker container, the `docker ps` command might help.


```
 netstat -ltnp 
```

**Comment by Daniel-Nashed** [comment]
did not hear anything back. I assume it is solved.
