### ISSUE TITLE
during build.sh fails to copy file from nginx host both ubuntu and centos

### ISSUE THREAD

**Issue by westteck** [IBM/domino-docker#47]
I have been trying to get this to work on both ubuntu 20. and 22, now centos 9 and am getting the same error. My last issue was partly because I did not have the latest 12.01 install files. I was able to finally find the in flexnet and use them for these last few attemps at installing a server with this repo. so far 3 attemps, 2 on ubuntu and one on centos. getting the same problem. I have been following the instructions very carefully step by step. here is the error:

--------------------------------------------------------------------------------
Downloading Domino Installation files ...
--------------------------------------------------------------------------------

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  148M  100  148M    0     0  90.8M      0  0:00:01  0:00:01 --:--:-- 90.9M

ERROR - File [http://172.17.0.2/Domino_12.0.1_Linux_English.tar] not downloaded correctly [2]

HASH         : [5550b67676f0cc62bf95619a10ef6675e127639b069f534ec44e8b3676783fbd]
SOFTWARE_FILE: [/tmp/install/software.txt]
CURRENT_FILE : [Domino_12.0.1_Linux_English.tar]

--- /tmp/install/software.txt ---

----------------------------------------------------------------------
it finishes with this:
----------------------------------------------------------------------

The command '/bin/sh -c $LocalInstallDir/install_domino.sh &&   rm -rf $LocalInstallDir' returned a non-zero code: 1

Image build failed!

**Comment by Daniel-Nashed** [comment]
This does not depend in the platform you are using . And I don't see anything obvious wrong.

when I run the install I am getting different numbers.
Your download is only 148 MB not 807MB.

Here is my output:

```
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  807M  100  807M    0     0  29.0M      0  0:00:27  0:00:27 --:--:-- 35.5M

Successfully downloaded, extracted & checked: [http://172.17.0.2/Domino_12.0.1_Linux_English.tar]
```

There is a way to check the binaries before the image process starts to run.

Can you try this to see if you get the right hash?

```
./build.sh domino -verifyonly
```
This tells the build script to verify the installer files and terminate.

If this does not give you a success, please check the hash manually:

```
sha256sum Domino_12.0.1_Linux_English.tar

a9d561b05f7b6850ed1230efa68ea1931cfdbb44685aad159613c29fa15e5eea  Domino_12.0.1_Linux_English.tar

```

It looks like your file is not correctly downloaded either from Flexnet or from NGINX to your build container.

The most simple check would be already checking the file size. 148 MB is not the right size for the Domino installer.

**Comment by westteck** [comment]
Your right, the files for Domino server did not upload correctly, the size was wrong. So I uploaded them again and ran ./build.sh domino -verifyonly and they both checked out as ok. I then ran the ./build.sh domino and 46 minutes later it finished. all worked as expected after that. Thanks

**Comment by Daniel-Nashed** [comment]
46 minutes? it should take 5-8 minutes. not longer. Not sure what is going on in your environment. But at most it should take 10 minutes on a very slow machine.

Glad the download problem is solved. I added the hash for a good reason. corrupted files can cause all kind of issues and are difficult to troubleshoot.
