### ISSUE TITLE
Problems starting Domino 12.0.2 container

### ISSUE THREAD

**Issue by rvsjoen** [IBM/domino-docker#56]
Seems to be problems with the startup scripts (ps missing?) when starting 12.0.2 container (coming from 12.0.1IF2)

Verfied that the Dockerfile is supposed to install procps-ng package which contains ps, but it is not available within the container

```
domino_domino.1.qeca3bkcn1he@usdocker01    | Using Domino config File [/etc/sysconfig/rc_domino_config]
domino_domino.1.qeca3bkcn1he@usdocker01    |
domino_domino.1.qeca3bkcn1he@usdocker01    | /opt/nashcom/startscript/rc_domino_script: line 1064: ps: command not found
domino_domino.1.qeca3bkcn1he@usdocker01    |
domino_domino.1.qeca3bkcn1he@usdocker01    | /opt/nashcom/startscript/rc_domino_script: line 1064: ps: command not found
domino_domino.1.qeca3bkcn1he@usdocker01    | Archived log file to '/local/notesdata/notes_221222_103030.log'
domino_domino.1.qeca3bkcn1he@usdocker01    | Removed LoadMon-Data '/local/notesdata/loadmon.ncf'
domino_domino.1.qeca3bkcn1he@usdocker01    |
domino_domino.1.qeca3bkcn1he@usdocker01    | Starting Domino for xLinux (notes)
domino_domino.1.qeca3bkcn1he@usdocker01    | Warning: LANG is not set!
domino_domino.1.qeca3bkcn1he@usdocker01    | done PID is 150
```

**Comment by Daniel-Nashed** [comment]
Yes the start scripts need the `ps` command. I don't see why it is not added.
Can you please provide more details.

Which base OS are you using to build the container and what does the build log say?

We never ran into any situation, where `ps` was not added to the container image during build.

This is not a start script problem. It's a container build issue.
And without more information it is impossible to say what is going wrong.

**Comment by rvsjoen** [comment]
Built using default options (CentOS8?)

```
./build.sh domino 12.0.2 -nomad
```

Ran a new build with "-from=leap" and that seems to work better.

**Comment by Daniel-Nashed** [comment]
It should also work with the default which is currently CentOS Stream 8 if you don't specify a specific image like SUSE Leap.
I don't see any reason why it should not work.
Did the build pull a fresh centos image? or was this an older image you had on disk?
In any case the build script should add the ps command if not available.

But this does not look like a build script image. As you mentioned it did install the package. 
So why should it not be there? 

You can run SUSE Leap or any other supported base images. But the standard base image should work the same way.

**Comment by Daniel-Nashed** [comment]
Here is output from my standard build. 
You can see it is installing the package.

What I understand from your initial description you get the same type of output.
Why should `ps` not be available afterwards in the image?

There is not much we can do to help in this case, beside asking you to pull an new base image and try again.

The container build is running as expected. I once had a missing package at build time and the next build did work correctly again. 


```
Downloading Packages:
procps-ng-3.3.15-9.el8.x86_64.rpm               3.6 MB/s | 329 kB     00:00
--------------------------------------------------------------------------------
Total                                           965 kB/s | 329 kB     00:00
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1
  Installing       : procps-ng-3.3.15-9.el8.x86_64                          1/1
  Running scriptlet: procps-ng-3.3.15-9.el8.x86_64                          1/1
  Verifying        : procps-ng-3.3.15-9.el8.x86_64                          1/1

Installed:
  procps-ng-3.3.15-9.el8.x86_64

Complete!
Last metadata expiration check: 0:01:05 ago on Thu Dec 22 11:28:38 2022.
Package glibc-langpack-en-2.28-220.el8.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Last metadata expiration check: 0:01:07 ago on Thu Dec 22 11:28:38 2022.
Dependencies resolved.
```

**Comment by Daniel-Nashed** [comment]
Cannot be reproduced here and we did not get any update. 
Please re-open if problem still exists.
