### ISSUE TITLE
Cannot use browser to import new image

### ISSUE THREAD

**Issue by john-dalsgaard** [IBM/domino-docker#59]
When I follow the guide to import the generated image then it seems to _create a container_ instead of just importing the image.

By enabling and using SSH, however, I could follow that path in the documentation to import the image 😄

**Comment by thampel** [comment]
I guess you are talking about the QNAP user interface? Yes, the "import" function there is trying to create a container as well. However, it should work when trying to import a file that is hosted on your NAS.

**Comment by john-dalsgaard** [comment]
I just wanted you to know that it didn't do exactly what the documentation said - or I misunderstood it? So perhaps just a little more explanation as to what you see - and what it does do in reality.

I managed to get around it by using SSH after uploading the file using File Station - so just for the next readers 😄
