### ISSUE TITLE
Faulty link to "GitHub issue tracker" in README.md

### ISSUE THREAD

**Issue by theold190** [IBM/domino-docker#65]
Right now link to "GitHub issue tracker" from [README.md](https://github.com/HCL-TECH-SOFTWARE/domino-container/blob/main/README.md) file in this repo points to https://github.com/HCL-TECH-SOFTWARE/domino-container/blob/main/issues. That link leads to a "404 - page not found".

The link that leads to issues on GitHub should probably be https://github.com/HCL-TECH-SOFTWARE/domino-container/issues

**Comment by Daniel-Nashed** [comment]
Thanks! Fixed along with a correction to the HCL License page.
The link you found was relative and that does not work from everywhere.
I changed it into and absolute link.
