### ISSUE TITLE
v14.0 FP2 Error in software.txt

### ISSUE THREAD

**Issue by finasoft** [IBM/domino-docker#70]
The software.txt file gives the name of v14 FP2 as Domino_140FP2_Linux.tar. The file downloaded from HCL Software download portal is Domino_1400FP2_Linux.tar. Hence the build of the v14FP2 image fails. One has to either rename the downloaded file of modify the software.txt

**Comment by Daniel-Nashed** [comment]
The software.txt has actually both names, just in case someone renames the file back to the expected name with one zero.

The comma separate list checks for the first name first and then for the second one.
14.0 FP2 is tested and should work. I have used it in multiple environments.

If did does not work for you, please provide logs.
I have just tested it again.

```
domino|14.0FP2|Domino_1400FP2_Linux.tar,Domino_140FP2_Linux.tar|XN8KJutYRTZokm1rq0Yjt|1785787ef9daefa126eb4c3db6973766d98c9274fb83b6d35ade929406bdc487
```

**Comment by finasoft** [comment]
The software.txt in this repository contains only:
domino|14.0FP2|Domino_140FP2_Linux.tar|XN8KJutYRTZokm1rq0Yjt|1785787ef9daefa126eb4c3db6973766d98c9274fb83b6d35ade929406bdc487
i.e. only one file.
I solved my problem by renaming the file.

**Comment by Daniel-Nashed** [comment]
looks like the changes have not been merged to the main branch.
I have just merged it along with the Leap changes.
Can you check again please ...
