### ISSUE TITLE
Selecting Ontime option prevents v12.0.2fp2 build

### ISSUE THREAD

**Issue by finasoft** [IBM/domino-docker#72]
DOMI option is only available for Domino v14 build. When you select the DOMI option and then you switch the Domino version from 14 to 12, the DOMI option disappears from the menu, but apparently (only my guess) it remains written somewhere in the configuration. When starting the build process the image build process fails.

When the DOMI option is deselected first, the image build process completes OK.

**Comment by Daniel-Nashed** [comment]
Can you explain where you see the DOMI option?

**Comment by finasoft** [comment]
Apologies, it is not DOMI option, it is (O) OnTime option.

**Comment by Daniel-Nashed** [comment]
I see. there might be a menu glitch I can look into if I can reproduce it.

**Comment by Daniel-Nashed** [comment]
Fixed it in the develop branch. Can you pull the changes and test again this resolves it.
Thanks

**Comment by finasoft** [comment]
Does "git clone ..." copies the develop branch? I am sorry my git experience is bellow zero.

**Comment by Daniel-Nashed** [comment]
it's already merged to main meanwhile.  
but git isn't too complicated.

```
git checkout develop
git pull
```

**Comment by finasoft** [comment]
I tried and my built failed with this error. It seems that when I have a configuration file in the /root directory with SOFTWARE_DIR=/local/software this configuration is not respected and it still tries to get the files from domino-container/software
![image](https://github.com/user-attachments/assets/f97b3e60-3fb7-49b4-8d45-77c3dfcded39)

**Comment by Daniel-Nashed** [comment]
sorry without better information I can't help you.

**Comment by finasoft** [comment]
I can build the image when the software files are in the domino-container/software directory. If I move the software files to /local/software directory and enable SOFTWARE_DIR=/local/software cfg variable. The image build fails.

**Comment by Daniel-Nashed** [comment]
works for me. If you don't provide more details about your config, I cannot help you.
It can be also a SELinux issue with the NGINX container. 
the devil is in the detail. you would need to go thru this step by step. 

it looks like the NGINX container which is used to serve the files does not get the file.
you can check the logs of the NGINX container to find details. 

```
docker logs nginx
```

**Comment by Daniel-Nashed** [comment]
please also check the owner and permissions of /local/software

**Comment by finasoft** [comment]
I am not really capable of giving simply because I do not know what to look for and where. I close the issue as there at least exist one way I can build the containers (I can have the files under domino-container/software dir. Thank you, anyway.

**Comment by Daniel-Nashed** [comment]
I gave you a couple of hints what to look for. 
And also explained what the problem could be.
If you can't give me more details and look into it from your side, there is not much I can do in addition.
I am sorry.

**Comment by Daniel-Nashed** [comment]
You are also leaving me here without detailed information about your environment.
It could be also an older Docker or Podman version.

There is a way to find out about your configuration:
```
./build.sh about
```
returns details about what is installed.
If one directory works and the other is not working it is either a config or permission issue usually.
